spring:
  # H2 인메모리 데이터베이스 설정 (개발 환경)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 콘솔 활성화 (브라우저에서 http://localhost:8080/h2-console 접속)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop  # 애플리케이션 시작 시 테이블 생성, 종료 시 삭제
    show-sql: true  # SQL 쿼리 콘솔 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  # DevTools 설정
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

# 로깅 레벨 (개발 환경은 더 상세하게)
logging:
  level:
    root: INFO
    com.back: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 서버 설정
server:
  port: 8080

---
# 개발 환경 설명
# - H2 인메모리 DB 사용으로 빠른 개발/테스트
# - ddl-auto: create-drop으로 매번 스키마 재생성
# - H2 콘솔 활성화로 데이터 확인 용이
# - 상세한 로깅으로 디버깅 편의성 제공
